# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('intersect_type', models.CharField(max_length=30)),
                ('collision_type', models.CharField(max_length=30)),
                ('automobile_count', models.IntegerField()),
                ('motorcycle_count', models.IntegerField()),
                ('bus_count', models.IntegerField()),
                ('small_truck_count', models.IntegerField()),
                ('heavy_truck_count', models.IntegerField()),
                ('suv_count', models.IntegerField()),
                ('van_count', models.IntegerField()),
                ('bicycle_count', models.IntegerField()),
                ('fatal_count', models.IntegerField()),
                ('injuery_count', models.IntegerField()),
                ('maj_inj_count', models.IntegerField()),
                ('sev_inj_count', models.IntegerField()),
                ('mcycle_death_count', models.IntegerField()),
                ('mcycle_maj_inj_count', models.IntegerField()),
                ('mcycle_sev_inj_count', models.IntegerField()),
                ('bicycle_death_count', models.IntegerField()),
                ('bicycle_maj_inj_count', models.IntegerField()),
                ('bicycle_sev_inj_count', models.IntegerField()),
                ('ped_count', models.IntegerField()),
                ('ped_death_count', models.IntegerField()),
                ('ped_maj_inj_count', models.IntegerField()),
                ('ped_sev_inj_count', models.IntegerField()),
                ('comm_veh_count', models.IntegerField()),
                ('max_severity_level', models.IntegerField()),
                ('has_intersection', models.BooleanField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('person_type', models.CharField(max_length=30)),
                ('restraint_helmet', models.CharField(max_length=30)),
            ],
        ),
    ]
